import Head from 'next/head';
import Image from 'next/image';
import Hero from './components/Hero';
import Main from './components/Main';
import Footer from './components/Footer';
import Slider from './components/Slider';
import { SliderData } from './components/SliderData'

export default function Home() {
  return (
    <div>
      <Head>
        <title>CT State Referee Association</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head >
      <Hero heading='CT State Referee Program' message='Holy Fucking Shit'/>
      <Main />
      <Footer />
      {/* <Slider slides={SliderData}/> */}
    </div>
  )
}
